steps:
    # Build the container image.
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    env:
      - 'TAG_NAME=0.0'
    args:
      - '-c'
      - |
        docker build -t gcr.io/${PROJECT_ID}/shorturl:latest -t gcr.io/${PROJECT_ID}/shorturl:0.0 .

images:
  - gcr.io/${PROJECT_ID}/shorturl:0.0
  - gcr.io/${PROJECT_ID}/shorturl:latest
